name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
        os:
          - ubuntu-latest
          - self-hosted

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build (typecheck) the project
        run: npm run build
      - name: Lint the project
        run: npm run lint
